SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) TOTAL_SALES
FROM (SELECT A.AUTHOR_ID
        , (SELECT AUTHOR_NAME FROM AUTHOR C WHERE A.AUTHOR_ID = C.AUTHOR_ID) AUTHOR_NAME
        , A.CATEGORY
        , SUM(B.SALES) * A.PRICE TOTAL_SALES
    FROM BOOK A
    JOIN (SELECT * FROM BOOK_SALES WHERE TO_CHAR(SALES_DATE, 'YYYY-MM-DD') LIKE '2022-01%') B ON A.BOOK_ID = B.BOOK_ID
    GROUP BY A.AUTHOR_ID, A.CATEGORY, A.PRICE)
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY 1, 3 DESC