SELECT TO_CHAR(os.SALES_DATE, 'YYYY') YEAR, TO_NUMBER(TO_CHAR(os.SALES_DATE, 'MM')) MONTH, ui.GENDER GENDER, COUNT(DISTINCT(os.USER_ID)) USERS
FROM USER_INFO ui
JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY TO_CHAR(os.SALES_DATE, 'YYYY'), TO_NUMBER(TO_CHAR(os.SALES_DATE, 'MM')), ui.GENDER
ORDER BY 1, 2, 3
