SELECT fp.PRODUCT_ID, fp.PRODUCT_NAME, SUM(fp.PRICE * fo.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT fp
JOIN FOOD_ORDER fo ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY fp.PRODUCT_ID, fp.PRODUCT_NAME
ORDER BY 3 DESC, 1