SELECT *
FROM (SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) * 0.01 AS FEE
    FROM (SELECT *
        FROM CAR_RENTAL_COMPANY_CAR 
        WHERE CAR_TYPE IN ('세단', 'SUV')) A
    JOIN (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        MINUS
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE '2022-11-01' BETWEEN TO_CHAR(START_DATE, 'YYYY-MM-DD') AND TO_CHAR(END_DATE, 'YYYY-MM-DD')
        OR '2022-11-30' BETWEEN TO_CHAR(START_DATE, 'YYYY-MM-DD') AND TO_CHAR(END_DATE, 'YYYY-MM-DD')) B ON A.CAR_ID = B.CAR_ID
    JOIN (SELECT * 
          FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
          WHERE DURATION_TYPE = '30일 이상') C ON A.CAR_TYPE = C.CAR_TYPE)
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC